{{- if .Values.global.cluster.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "quellenpanel.fullname" . }}
  labels: {{ include "quellenpanel.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{ include "quellenpanel.selectorLabels" . | nindent 6 }}
{{- end }}
